[package]
name = "marshmallow-recipe"
version = "0.0.70"
edition = "2021"

[lib]
name = "_nuked"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value", "arbitrary_precision"] }
once_cell = "1.19"
encoding_rs = "0.8"
uuid = "1.11"
regex = "1.10"
