[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "marshmallow-recipe-speedup"
version = "0.0.1"
description = "Rust acceleration for marshmallow-recipe"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "Yury Pliner", email = "yury.pliner@gmail.com"}
]

[project.urls]
Homepage = "https://github.com/anna-money/marshmallow-recipe"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "marshmallow_recipe_speedup._core"

[tool.maturin.environment]
PYO3_USE_ABI3_FORWARD_COMPATIBILITY = "1"
